source "https://api.berkshelf.com"

cookbook 'deploy', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'deploy'
cookbook 'opsworks_commons', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'opsworks_commons'
cookbook 'scm_helper', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'scm_helper'
cookbook 'mod_php5_apache2', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'mod_php5_apache2'
cookbook 'ssh_users', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'ssh_users'
cookbook 'opsworks_agent_monit', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'opsworks_agent_monit'
cookbook 'opsworks_java', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'opsworks_java'
cookbook 'opsworks_aws_flow_ruby', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'opsworks_aws_flow_ruby'
cookbook 'gem_support', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'gem_support'
cookbook 'opsworks_nodejs', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'opsworks_nodejs'
cookbook 'opsworks_initial_setup', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'opsworks_initial_setup'
cookbook 'mysql', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'mysql'
cookbook 'dependencies', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'dependencies'
cookbook 'opsworks_ganglia', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'opsworks_ganglia'
cookbook 'opsworks_sidekiq', '>= 0.0.0', github: 'aadamson/opsworks_sidekiq'
cookbook 'monit', github: 'aadamson/opsworks-cookbooks', branch: 'master-chef-11.10', rel: 'monit'
